name       : xkcdpass
version    : 1.19.2
release    : 3
source     :
    - https://github.com/redacted/XKCD-password-generator/archive/refs/tags/xkcdpass-1.19.2.tar.gz : 6d353a7705cc49f58f5245c3dd095adef01edea644d796b75da25df791b7e75b
homepage   : https://github.com/redacted/XKCD-password-generator
license    : BSD-3-Clause
component  : security
summary    : A flexible and scriptable password generator which generates strong passphrases, inspired by XKCD comic 936
description: |
    A flexible and scriptable password generator which generates strong passphrases, inspired by XKCD comic 936
build      : |
    %python3_setup
install    : |
    %python3_install
    install -Dm00644 xkcdpass.1  $installdir/usr/share/man/man1/xkcdpass.1
check      : |
    %python3_test
