name       : xkcdpass
version    : 1.19.3
release    : 6
source     :
    - https://github.com/redacted/XKCD-password-generator/archive/refs/tags/xkcdpass-1.19.3.tar.gz : 8ac1e1778c6c9bb1725816244695c79c622414f6937406be1eb10606de166340
homepage   : https://github.com/redacted/XKCD-password-generator
license    : BSD-3-Clause
component  : security
summary    : A flexible and scriptable password generator which generates strong passphrases, inspired by XKCD comic 936
description: |
    A flexible and scriptable password generator which generates strong passphrases, inspired by XKCD comic 936
build      : |
    %python3_setup
install    : |
    %python3_install
    install -Dm00644 xkcdpass.1  $installdir/usr/share/man/man1/xkcdpass.1
#check      : |
#    %python3_test
