name       : xkcdpass
version    : 1.17.6
release    : 2
source     :
    - https://files.pythonhosted.org/packages/cc/3a/065130b94cb57cbbd7057e4627cc15bcb16bb9f9d9ef6290e8138273b7a6/xkcdpass-1.17.6.tar.gz : 9e89291c927671ef5616a9c9ebaa118b7b1b844e188474d53529d1be8a961a3e
homepage   : https://github.com/redacted/XKCD-password-generator
license    : BSD-3-Clause
component  : security
summary    : A flexible and scriptable password generator which generates strong passphrases, inspired by XKCD comic 936
description: |
    A flexible and scriptable password generator which generates strong passphrases, inspired by XKCD comic 936
build      : |
    %python3_setup
install    : |
    %python3_install
    install -Dm00644 xkcdpass.1  $installdir/usr/share/man/man1/xkcdpass.1
check      : |
    %python3_test
