name       : xkcdpass
version    : 1.17.3
release    : 1
source     :
    - https://github.com/redacted/XKCD-password-generator/archive/xkcdpass-1.17.3.tar.gz : 793aa1803360033cefa24b386abb0f11f815ffd95824026605fe398e98f9efd4
homepage   : https://github.com/redacted/XKCD-password-generator
license    : BSD-3-Clause
component  : security
summary    : A flexible and scriptable password generator which generates strong passphrases, inspired by XKCD comic 936
description: |
    A flexible and scriptable password generator which generates strong passphrases, inspired by XKCD comic 936
build      : |
    %python3_setup
install    : |
    %python3_install
    install -Dm00644 xkcdpass.1  $installdir/usr/share/man/man1/xkcdpass.1
check      : |
    %python3_test
